version: "3.9"
services:
  backend:
    build:
      context: .
      target: backend
    depends_on:
      - "redis-server"
      - "mongo-server"
    ports:
      - "3000:3000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:123456@mongo-server:27017
      - REDIS_CONNECTION_STRING=redis://redis-server:6379
      - PORT=3000
  backend-dev:
    build:
      context: .
      target: development
    depends_on:
      - "redis-server"
      - "mongo-server"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/pingu-api
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:123456@mongo-server:27017
      - REDIS_CONNECTION_STRING=redis://redis-server:6379
      - PORT=3001
  redis-server:
    image: "redis:alpine"
  mongo-server:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456