import SOCKET_EVENTS from './SocketEvents';

const USER_TYPES = {
  OWNER: 'owner',
  MODERATOR: 'moderator',
  GUEST: 'guest',
};

const ACTIONS = {
  [SOCKET_EVENTS.UPDATE_PLAYLIST]: [USER_TYPES.OWNER, USER_TYPES.MODERATOR],
  [SOCKET_EVENTS.KICK_USER]: [USER_TYPES.OWNER],
  [SOCKET_EVENTS.UPDATE_VIDEO_STATUS]: [USER_TYPES.OWNER, USER_TYPES.MODERATOR],
  [SOCKET_EVENTS.CHANGE_VIDEO_DURATION]: [USER_TYPES.OWNER, USER_TYPES.MODERATOR],
  [SOCKET_EVENTS.SKIP_VIDEO]: [USER_TYPES.OWNER, USER_TYPES.MODERATOR],
};

export {
  USER_TYPES,
  ACTIONS,
};
